/* ═══════════════════════════════════════════
   VELMORA — shared config & catalogue data
   Edit prices / WhatsApp number / products here.
   ═══════════════════════════════════════════ */
window.VELMORA = {
  whatsapp: "96181772615",
  imgPath: "assets/img/items/",
  prices: {
    "50ml":  { now: 10, was: 12 },
    "100ml": { now: 15, was: 18 }
  },

  /* Homepage "Signature Edit" — files must exist in PRODUCTS below */
  featured: [
    "dior-sauvage.jpg",
    "bleu-de-chanel-eau-de-parfum-men.jpg",
    "maison-francis-kurkdjian-baccarat-rouge-540.jpg",
    "chanel-coco-mademoiselle.jpg",
    "kayali-vanilla-28.jpg"
  ],

  /* Scent finder: answer to "scent family" → product file */
  quiz: {
    fresh:  { file: "dior-sauvage.jpg", note: "A powerful fresh spicy-aromatic with bergamot, lavender and ambroxan — bold and versatile for day or night." },
    floral: { file: "chanel-coco-mademoiselle.jpg", note: "An elegant floral-oriental with orange, jasmine and patchouli — sophisticated and timeless." },
    woody:  { file: "maison-francis-kurkdjian-baccarat-rouge-540.jpg", note: "A luxurious amber-woody scent with saffron, cedar and ambroxan — mysterious and intoxicating." },
    sweet:  { file: "kayali-vanilla-28.jpg", note: "A warm sweet gourmand with vanilla, tonka bean and amber — comforting and addictive." },
    refined:{ file: "bleu-de-chanel-eau-de-parfum-men.jpg", note: "A fresh woody-aromatic with citrus, incense and cedar — refined and effortlessly masculine." }
  },

  products: [
  {"brand": "Azzaro", "name": "Chrome", "file": "azzaro-chrome-men.jpeg"},
  {"brand": "Azzaro", "name": "The Most Wanted", "file": "azzaro-the-most-wanted-men.jpeg"},
  {"brand": "Azzaro", "name": "Wanted by Night", "file": "azzaro-wanted-by-night-men.jpeg"},
  {"brand": "Azzaro", "name": "Wanted", "file": "azzaro-wanted-men.jpeg"},
  {"brand": "Azzaro", "name": "Chrome Extreme", "file": "azzaro-chrome-extreme-men.jpg"},
  {"brand": "Rabanne", "name": "1 Million Gold", "file": "paco-rabanne-1-million-gold.jpg"},
  {"brand": "Chanel", "name": "Bleu de Chanel Eau de Parfum", "file": "bleu-de-chanel-eau-de-parfum-men.jpg"},
  {"brand": "Boss", "name": "The Scent", "file": "boss-the-scent.jpg"},
  {"brand": "Britney Spears", "name": "Fantasy", "file": "britney-spears-fantasy-woman.jpg"},
  {"brand": "Burberry", "name": "Hero", "file": "burberry-hero-men.jpeg"},
  {"brand": "Burberry", "name": "Touch", "file": "burberry-touch-men.jpeg"},
  {"brand": "Burberry", "name": "Woman", "file": "burberry-woman-woman.jpeg"},
  {"brand": "Burberry", "name": "Her", "file": "burberry-her-woman.jpg"},
  {"brand": "Burberry", "name": "Her Elixir", "file": "burberry-her-elixir-woman.jpg"},
  {"brand": "Burberry", "name": "Goddess", "file": "burberry-goddes-woman.jpg"},
  {"brand": "Bvlgari", "name": "Aqva Marine", "file": "bvlgari-aqva-marine-men.jpg"},
  {"brand": "Bvlgari", "name": "Goldea", "file": "bvlgari-goldea-woman.jpg"},
  {"brand": "Bvlgari", "name": "Man in Black", "file": "bvlgari-man-in-black-men.jpg"},
  {"brand": "Bvlgari", "name": "Omnia Crystaline", "file": "bvlgari-omnia-crystaline-woman.jpg"},
  {"brand": "Bvlgari", "name": "Tygar", "file": "bvlgari-tygar-men.jpg"},
  {"brand": "Calvin Klein", "name": "CK One", "file": "calvin-klein-ck-one.jpg"},
  {"brand": "Calvin Klein", "name": "Euphoria", "file": "calvin-klein-euphoria.jpg"},
  {"brand": "Carolina Herrera", "name": "212 VIP Black", "file": "carolina-herrera-212-vip-black.jpg"},
  {"brand": "Carolina Herrera", "name": "212 VIP Rose", "file": "carolina-herrera-212-vip-rose.jpg"},
  {"brand": "Carolina Herrera", "name": "Bad Boy", "file": "carolina-herrera-bad-boy.jpg"},
  {"brand": "Carolina Herrera", "name": "CH Men Prive", "file": "carolina-herrera-ch-men-prive.jpg"},
  {"brand": "Carolina Herrera", "name": "Good Girl Midnight", "file": "carolina-herrera-good-girl-midnight.jpg"},
  {"brand": "Carolina Herrera", "name": "Good Girl Blush", "file": "carolina-herrera-good=girl-blush.jpg"},
  {"brand": "Carolina Herrera", "name": "Good Girl", "file": "carolina-herrera-good-girl60805.jpg"},
  {"brand": "Chanel", "name": "Allure Homme Sport", "file": "chanel-allure-homme-sport-men.jpg"},
  {"brand": "Chanel", "name": "Chance Eau Tendre", "file": "chanel-chance-eau0tendre.jpg"},
  {"brand": "Chanel", "name": "Coco Mademoiselle", "file": "chanel-coco-mademoiselle.jpg"},
  {"brand": "Chanel", "name": "Coco Noir", "file": "chanel-coco-noir.jpg"},
  {"brand": "Chanel", "name": "Egoiste Platinum", "file": "chanel-egoiste-platinum-men.jpg"},
  {"brand": "Chloe", "name": "Chloe", "file": "chloe-chloe.jpg"},
  {"brand": "Davidoff", "name": "Cool Water Woman (Classic)", "file": "cool-water-woman.jpg"},
  {"brand": "Creed", "name": "Aventus", "file": "creed-aventus.jpg"},
  {"brand": "Creed", "name": "Aventus Absolu", "file": "creed-aventus-absolu.jpg"},
  {"brand": "Creed", "name": "Aventus for Her", "file": "creed-aventus-for-her.jpg"},
  {"brand": "Creed", "name": "Carmina", "file": "creed-carmina.jpg"},
  {"brand": "Creed", "name": "Silver Mountain Water", "file": "creed-silver-mountain-water.jpg"},
  {"brand": "Creed", "name": "Virgin Island Water", "file": "creed-virgin-island-water.jpg"},
  {"brand": "Davidoff", "name": "Cool Water", "file": "davidoff-cool-water.jpg"},
  {"brand": "Davidoff", "name": "Cool Water Woman", "file": "davidoff-cool-water-woman.jpg"},
  {"brand": "Diesel", "name": "Only the Brave", "file": "diesel-only-the-brave.jpg"},
  {"brand": "Dior", "name": "Addict", "file": "dior-addict.jpg"},
  {"brand": "Dior", "name": "Amber Nuit", "file": "dior-amber-nuit-unisex.jpg"},
  {"brand": "Dior", "name": "Fahrenheit", "file": "dior-fahrenheit.jpg"},
  {"brand": "Dior", "name": "Homme", "file": "dior-homme.jpg"},
  {"brand": "Dior", "name": "Homme Intense", "file": "dior-homme-intense.jpg"},
  {"brand": "Dior", "name": "Hypnotic Poison", "file": "dior-hypnotic-poison.jpg"},
  {"brand": "Dior", "name": "Jadore", "file": "dior-jadore.jpg"},
  {"brand": "Dior", "name": "Miss Dior Blooming Bouquet", "file": "dior-miss-dior-blooming-bouquet.jpg"},
  {"brand": "Dior", "name": "Oud Ispahan", "file": "dior-oud-ispahan.jpg"},
  {"brand": "Dior", "name": "Sauvage", "file": "dior-sauvage.jpg"},
  {"brand": "Dior", "name": "Sauvage Elixir", "file": "dior-sauvage-elixir.jpg"},
  {"brand": "Dior", "name": "Vanilla Diorama", "file": "dior-vanilla-diorama-unisex.jpg"},
  {"brand": "Dolce & Gabbana", "name": "The One", "file": "dolce-&-gabbana-the-one.jpg"},
  {"brand": "Dolce & Gabbana", "name": "K", "file": "dolce-&-gabbana-k.jpg"},
  {"brand": "Dolce & Gabbana", "name": "Light Blue", "file": "dolce-&-gabbana-light-blue.jpg"},
  {"brand": "Dolce & Gabbana", "name": "Light Blue Forever", "file": "dolce-&-gabbana-light-blue-forever.jpg"},
  {"brand": "Dolce & Gabbana", "name": "L'Imperatrice", "file": "dolce-&-gabbana-limperatrice.jpg"},
  {"brand": "Dolce & Gabbana", "name": "Devotion", "file": "dolce-&-gabbana-dovotion.jpg"},
  {"brand": "Dunhill", "name": "Desire Blue", "file": "dunhill-desire-blue.jpg"},
  {"brand": "Elie Saab", "name": "Girl of Now", "file": "elie-saab-girl-of-now.jpg"},
  {"brand": "Elie Saab", "name": "Le Parfum", "file": "elie-saab-le-parfum.jpg"},
  {"brand": "Elie Saab", "name": "L'Homme", "file": "elie-saab-lhomme.jpg"},
  {"brand": "Escada", "name": "Sunset", "file": "escada-sunset.jpg"},
  {"brand": "Giorgio Armani", "name": "Acqua di Gio Profondo", "file": "acqua-di-gio-profondo-giorgio-armani.jpg"},
  {"brand": "Giorgio Armani", "name": "Acqua di Gio Profumo", "file": "acqua-di-gio-profumo-giorgio-armani.jpg"},
  {"brand": "Giorgio Armani", "name": "My Way", "file": "my-way-giorgio-armani.jpg"},
  {"brand": "Giorgio Armani", "name": "Si", "file": "si-giorgio-armani.jpg"},
  {"brand": "Givenchy", "name": "Gentleman Boise", "file": "gentelman-boisee-givenchy.jpg"},
  {"brand": "Givenchy", "name": "Gentleman Reserve Privee", "file": "gentelman-reserve-privee.jpg"},
  {"brand": "Givenchy", "name": "Irresistible Rose Velvet", "file": "irresistible-rose-velvet-givenchy.jpg"},
  {"brand": "Grand Soir", "name": "Grand Soir", "file": "grand-soir.jpg"},
  {"brand": "Gucci", "name": "Bloom", "file": "gucci-bloom.jpg"},
  {"brand": "Gucci", "name": "Flora", "file": "gucci-flora.jpg"},
  {"brand": "Gucci", "name": "Guilty", "file": "guilty-gucci.jpg"},
  {"brand": "Guerlain", "name": "Insolence", "file": "guerlain-insolence.jpg"},
  {"brand": "Guerlain", "name": "L'Homme Ideal", "file": "lhomme-ideal-guerlain.jpg"},
  {"brand": "Hermes", "name": "Terre d'Hermes", "file": "hermes-terre-dhermes.jpg"},
  {"brand": "Hermes", "name": "Voyage d'Hermes", "file": "hermes-voyage-dhermes.jpg"},
  {"brand": "Boss", "name": "The Scent (Hugo Boss)", "file": "hugo-boss-the-scent.jpg"},
  {"brand": "Boss", "name": "Boss The Scent Elixir", "file": "hugo-boss-boss-the-scent-elixir.jpg"},
  {"brand": "Jean Paul Gaultier", "name": "Le Male", "file": "jean-paul-gaultier-le-male.jpg"},
  {"brand": "Jean Paul Gaultier", "name": "Le Beau Le Parfum", "file": "jean-paul-gaultier-le-beau-le-parfum.jpg"},
  {"brand": "Jean Paul Gaultier", "name": "Scandal", "file": "jean-paul-gaultier-scandal.jpg"},
  {"brand": "Kayali", "name": "Eden Juice Apple", "file": "kayali-eden-juice-apple.jpg"},
  {"brand": "Kayali", "name": "Vanilla 28", "file": "kayali-vanilla-28.jpg"},
  {"brand": "Kayali", "name": "Yum Boujee Marshmallow", "file": "kayali-yum-boujee-marshmellow.jpg"},
  {"brand": "Lacoste", "name": "L.12.12 Blanc", "file": "lacoste-l.12.12-blanc.jpg"},
  {"brand": "Lancome", "name": "Idole", "file": "lancome-idole.jpg"},
  {"brand": "Lancome", "name": "La Vie Est Belle", "file": "lancome-paris-la vie-est-belle.jpg"},
  {"brand": "Louis Vuitton", "name": "Afternoon Swim", "file": "louis-vuitton-afternoon-swim.jpg"},
  {"brand": "Louis Vuitton", "name": "On the Beach", "file": "louis-vuitton-on-the-beach.jpg"},
  {"brand": "Maison Francis Kurkdjian", "name": "Baccarat Rouge 540", "file": "maison-francis-kurkdjian-baccarat-rouge-540.jpg"},
  {"brand": "Maison Francis Kurkdjian", "name": "724", "file": "maison-francis-kurdjian-724.jpg"},
  {"brand": "Maison Francis Kurkdjian", "name": "Gentle Fluidity", "file": "maison-francis-kurkdjian-gentle-fluidity.jpg"},
  {"brand": "Maison Francis Kurkdjian", "name": "Oud Satin Mood", "file": "maison-francis-kurkdjian-oud-satin-mood.jpg"},
  {"brand": "Mancera", "name": "Instant Crush", "file": "mancera-instant-crush-eau-de-parfum40.jpg"},
  {"brand": "Mancera", "name": "Paris Cedrat Boise", "file": "mancera-paris-cedrat-boise.jpg"},
  {"brand": "Montblanc", "name": "Legend EDP", "file": "montblanc-legend-edp.jpg"},
  {"brand": "Montblanc", "name": "Legend Night", "file": "montblanc-legend-night.jpg"},
  {"brand": "Mugler", "name": "Alien", "file": "mugler-alien.jpg"},
  {"brand": "Narciso Rodriguez", "name": "For Her Intense", "file": "narciso-rodriguez-for-her-intense.jpg"},
  {"brand": "Narciso Rodriguez", "name": "Pure Musc", "file": "narciso-rodriguez-pure-musc.jpg"},
  {"brand": "Nina Ricci", "name": "Nina", "file": "nina-ricci-nina.jpg"},
  {"brand": "Parfums de Marly", "name": "Delina", "file": "parfums-de-marly-delina.jpg"},
  {"brand": "Parfums de Marly", "name": "Greenley", "file": "parfums-de-marly-greenley.jpg"},
  {"brand": "Parfums de Marly", "name": "Kalan", "file": "parfums-de-marly-kalan.jpg"},
  {"brand": "Parfums de Marly", "name": "Layton", "file": "parfums-de-marly-layton.jpg"},
  {"brand": "Portrait of a Lady", "name": "Portrait of a Lady", "file": "portrait-of-a-lady-frederic-male.jpg"},
  {"brand": "Rabanne", "name": "Invictus Parfum", "file": "rabanne-invictus-parfum.jpg"},
  {"brand": "Rabanne", "name": "Lady Million", "file": "rabanne-lady-million.jpg"},
  {"brand": "Rabanne", "name": "Olympya", "file": "rabanne-olympea.jpg"},
  {"brand": "Roberto Cavalli", "name": "Paradise", "file": "roberto-cavalli-paradise.jpg"},
  {"brand": "Stronger With You", "name": "Absolutely", "file": "stronger-with-you-absolutley.jpg"},
  {"brand": "Stronger With You", "name": "Intensely", "file": "stronger-with-you-intensely.jpg"},
  {"brand": "Tom Ford", "name": "Tobacco Vanille", "file": "tom-ford-tobacco-vanille.jpg"},
  {"brand": "Valentino", "name": "Donna Born in Roma", "file": "valentino-donna-born-in-roma.jpg"},
  {"brand": "Valentino", "name": "Uomo Born in Roma", "file": "valentino-uomo-born-in-roma.jpg"},
  {"brand": "Versace", "name": "Bright Crystal", "file": "versace-bright-crystal.jpg"},
  {"brand": "Versace", "name": "Crystal Noir", "file": "versace-crystal-noir.jpg"},
  {"brand": "Versace", "name": "Eros Flame", "file": "versace-eros-flame.jpg"},
  {"brand": "Versace", "name": "Eros", "file": "versace-eros.jpg"},
  {"brand": "Victoria's Secret", "name": "Bombshell", "file": "victorias-secret-bombshell.jpg"},
  {"brand": "Victoria's Secret", "name": "Tease Sugar Fleur", "file": "victorias-secret-tease-sugar-fleur.jpg"},
  {"brand": "Victoria's Secret", "name": "Very Sexy Orchid", "file": "victorias-secret-very-sexy-orchid.jpg"},
  {"brand": "Avon", "name": "Far Away", "file": "avon-far-away-woman.jpg"}
  ]
};

/* handy lookups */
window.VELMORA.byFile = Object.fromEntries(window.VELMORA.products.map(p => [p.file, p]));
window.VELMORA.img = file => window.VELMORA.imgPath + file;
